// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-5_75wkOHOJKtRKbq8Qo5wvyx1xclNR8',
    appId: '1:1058877404281:web:81870a5b92a14bf4ea10a8',
    messagingSenderId: '1058877404281',
    projectId: 'katahari-b10e4',
    authDomain: 'katahari-b10e4.firebaseapp.com',
    storageBucket: 'katahari-b10e4.firebasestorage.app',
    measurementId: 'G-Y49EWB4L44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBselKd-6tMuJiqQPe6FTEqbyKdbbwoyzo',
    appId: '1:1058877404281:android:b1dcd9665615b99dea10a8',
    messagingSenderId: '1058877404281',
    projectId: 'katahari-b10e4',
    storageBucket: 'katahari-b10e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCd0RwPurqENrIUdeEGQ_fvxu8R57-azM',
    appId: '1:1058877404281:ios:12cbbb0d544ba8b2ea10a8',
    messagingSenderId: '1058877404281',
    projectId: 'katahari-b10e4',
    storageBucket: 'katahari-b10e4.firebasestorage.app',
    iosBundleId: 'com.example.katahari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCd0RwPurqENrIUdeEGQ_fvxu8R57-azM',
    appId: '1:1058877404281:ios:12cbbb0d544ba8b2ea10a8',
    messagingSenderId: '1058877404281',
    projectId: 'katahari-b10e4',
    storageBucket: 'katahari-b10e4.firebasestorage.app',
    iosBundleId: 'com.example.katahari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-5_75wkOHOJKtRKbq8Qo5wvyx1xclNR8',
    appId: '1:1058877404281:web:e681f539bffb895eea10a8',
    messagingSenderId: '1058877404281',
    projectId: 'katahari-b10e4',
    authDomain: 'katahari-b10e4.firebaseapp.com',
    storageBucket: 'katahari-b10e4.firebasestorage.app',
    measurementId: 'G-94QQXH9TWD',
  );
}
